### PR TITLE
#9 - breadcrumbs confuse

### PR DESCRIPTION
**Pull request by marcosrjjunior**
#9  

:heavy_check_mark:
breadok1
:heavy_check_mark:
breadok2
:heavy_check_mark:
breadok3

### CODE REVIEW

**Comment by Pierstoval** [comment]
Thanks for this fix 👍 

However, can you put the logic in the `findFrontPages()` method of the repository to make the controller lighter?

**Comment by marcosrjjunior** [comment]
Sure, in a minute : )

**Comment by marcosrjjunior** [comment]
?

**Review by Pierstoval — APPROVED** [review]

**Comment by Pierstoval** [comment]
Let's merge and fix tests in other commits

**Comment by marcosrjjunior** [comment]
Thanks @Pierstoval, waiting for a new release : )

**Pull request merged**
